//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xdAntiSpy.Locales {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xdAntiSpy.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable File Explorer Ads ähnelt.
        /// </summary>
        internal static string _adsFileExplorerAds {
            get {
                return ResourceManager.GetString("_adsFileExplorerAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable ads in File Explorer. ähnelt.
        /// </summary>
        internal static string _adsFileExplorerAds_desc {
            get {
                return ResourceManager.GetString("_adsFileExplorerAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Finish Setup Ads ähnelt.
        /// </summary>
        internal static string _adsFinishSetupAds {
            get {
                return ResourceManager.GetString("_adsFinishSetupAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable ads in File Explorer. ähnelt.
        /// </summary>
        internal static string _adsFinishSetupAds_desc {
            get {
                return ResourceManager.GetString("_adsFinishSetupAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Lock Screen Tips and Ads ähnelt.
        /// </summary>
        internal static string _adsLockScreenAds {
            get {
                return ResourceManager.GetString("_adsLockScreenAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable tips and ads on the lock screen. ähnelt.
        /// </summary>
        internal static string _adsLockScreenAds_desc {
            get {
                return ResourceManager.GetString("_adsLockScreenAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Personalized Ads ähnelt.
        /// </summary>
        internal static string _adsPersonalizedAds {
            get {
                return ResourceManager.GetString("_adsPersonalizedAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable personalized ads. ähnelt.
        /// </summary>
        internal static string _adsPersonalizedAds_desc {
            get {
                return ResourceManager.GetString("_adsPersonalizedAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Settings Ads ähnelt.
        /// </summary>
        internal static string _adsSettingAds {
            get {
                return ResourceManager.GetString("_adsSettingAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable ads in settings. ähnelt.
        /// </summary>
        internal static string _adsSettingAds_desc {
            get {
                return ResourceManager.GetString("_adsSettingAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Start menu Ads ähnelt.
        /// </summary>
        internal static string _adsStartmenuAds {
            get {
                return ResourceManager.GetString("_adsStartmenuAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable ads in the start menu. ähnelt.
        /// </summary>
        internal static string _adsStartmenuAds_desc {
            get {
                return ResourceManager.GetString("_adsStartmenuAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Tailored experiences ähnelt.
        /// </summary>
        internal static string _adsTailoredExperiences {
            get {
                return ResourceManager.GetString("_adsTailoredExperiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tailored Experiences allows Microsoft to get information from you to deliver personalized tips, ads, and recommendations. Many people would call this telemetry, or even spying. ähnelt.
        /// </summary>
        internal static string _adsTailoredExperiences_desc {
            get {
                return ResourceManager.GetString("_adsTailoredExperiences_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable General Tips and Ads ähnelt.
        /// </summary>
        internal static string _adsTipsAndSuggestions {
            get {
                return ResourceManager.GetString("_adsTipsAndSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable general tips and ads. ähnelt.
        /// </summary>
        internal static string _adsTipsAndSuggestions_desc {
            get {
                return ResourceManager.GetString("_adsTipsAndSuggestions_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Welcome Experience Ads ähnelt.
        /// </summary>
        internal static string _adsWelcomeExperienceAds {
            get {
                return ResourceManager.GetString("_adsWelcomeExperienceAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable ads in the welcome experience. ähnelt.
        /// </summary>
        internal static string _adsWelcomeExperienceAds_desc {
            get {
                return ResourceManager.GetString("_adsWelcomeExperienceAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t Show Copilot in Taskbar ähnelt.
        /// </summary>
        internal static string _aiCopilotTaskbar {
            get {
                return ResourceManager.GetString("_aiCopilotTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable Copilot in Taskbar. ähnelt.
        /// </summary>
        internal static string _aiCopilotTaskbar_desc {
            get {
                return ResourceManager.GetString("_aiCopilotTaskbar_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dont&apos; Allow Windows to save snapshots of your screen ähnelt.
        /// </summary>
        internal static string _aiRecallCurrentUser {
            get {
                return ResourceManager.GetString("_aiRecallCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable Recall from saving snapshots of your screen. ähnelt.
        /// </summary>
        internal static string _aiRecallCurrentUser_desc {
            get {
                return ResourceManager.GetString("_aiRecallCurrentUser_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t Allow system-wide snapshots ähnelt.
        /// </summary>
        internal static string _aiRecallLocalMachine {
            get {
                return ResourceManager.GetString("_aiRecallLocalMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable system-wide snapshots. ähnelt.
        /// </summary>
        internal static string _aiRecallLocalMachine_desc {
            get {
                return ResourceManager.GetString("_aiRecallLocalMachine_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adblock ähnelt.
        /// </summary>
        internal static string _catAdblock {
            get {
                return ResourceManager.GetString("_catAdblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AI/Copilot and Recall ähnelt.
        /// </summary>
        internal static string _catAI {
            get {
                return ResourceManager.GetString("_catAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gaming ähnelt.
        /// </summary>
        internal static string _catGaming {
            get {
                return ResourceManager.GetString("_catGaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft Edge ähnelt.
        /// </summary>
        internal static string _catMSEdge {
            get {
                return ResourceManager.GetString("_catMSEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy ähnelt.
        /// </summary>
        internal static string _catPrivacy {
            get {
                return ResourceManager.GetString("_catPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System ähnelt.
        /// </summary>
        internal static string _catSystem {
            get {
                return ResourceManager.GetString("_catSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taskbar ähnelt.
        /// </summary>
        internal static string _catTaskbar {
            get {
                return ResourceManager.GetString("_catTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Browser sign in and sync services ähnelt.
        /// </summary>
        internal static string _edgeBrowserSignin {
            get {
                return ResourceManager.GetString("_edgeBrowserSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This setting controls whether a user can sign into Microsoft Edge with an account to use services such as sync and single sign on ähnelt.
        /// </summary>
        internal static string _edgeBrowserSignin_desc {
            get {
                return ResourceManager.GetString("_edgeBrowserSignin_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t Show Sponsored links in new tab page ähnelt.
        /// </summary>
        internal static string _edgeDefaultTopSites {
            get {
                return ResourceManager.GetString("_edgeDefaultTopSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide default top sites from the new tab page in Microsoft Edge ähnelt.
        /// </summary>
        internal static string _edgeDefaultTopSites_desc {
            get {
                return ResourceManager.GetString("_edgeDefaultTopSites_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Microsoft Edge as default browser ähnelt.
        /// </summary>
        internal static string _edgeDefautBrowserSetting {
            get {
                return ResourceManager.GetString("_edgeDefautBrowserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Force Edge to stop asking to change default browser. ähnelt.
        /// </summary>
        internal static string _edgeDefautBrowserSetting_desc {
            get {
                return ResourceManager.GetString("_edgeDefautBrowserSetting_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Access to Collections feature ähnelt.
        /// </summary>
        internal static string _edgeEdgeCollections {
            get {
                return ResourceManager.GetString("_edgeEdgeCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables users to access the Collections feature, allowing them to gather, organize, share, and export content more efficiently with Office integration. ähnelt.
        /// </summary>
        internal static string _edgeEdgeCollections_desc {
            get {
                return ResourceManager.GetString("_edgeEdgeCollections_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Shopping assistant in Microsoft Edge ähnelt.
        /// </summary>
        internal static string _edgeEdgeShoppingAssistant {
            get {
                return ResourceManager.GetString("_edgeEdgeShoppingAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shopping in Microsoft Edge feature will automatically find you the best prices and coupons from across the web as you shop. ähnelt.
        /// </summary>
        internal static string _edgeEdgeShoppingAssistant_desc {
            get {
                return ResourceManager.GetString("_edgeEdgeShoppingAssistant_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t Show First Run Experience ähnelt.
        /// </summary>
        internal static string _edgeFirstRunExperience {
            get {
                return ResourceManager.GetString("_edgeFirstRunExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide home screen and &apos;Getting Started&apos; on initial launch (from version 80 onwards). ähnelt.
        /// </summary>
        internal static string _edgeFirstRunExperience_desc {
            get {
                return ResourceManager.GetString("_edgeFirstRunExperience_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Gamer Mode ähnelt.
        /// </summary>
        internal static string _edgeGamerMode {
            get {
                return ResourceManager.GetString("_edgeGamerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft Edge Gamer Mode allows gamers to personalize their browser with gaming themes and gives them the option of enabling Efficiency Mode for PC gaming, the Gaming feed on new tabs, sidebar apps for gamers, and more. ähnelt.
        /// </summary>
        internal static string _edgeGamerMode_desc {
            get {
                return ResourceManager.GetString("_edgeGamerMode_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Copilot Symbol in Edge ähnelt.
        /// </summary>
        internal static string _edgeHubsSidebar {
            get {
                return ResourceManager.GetString("_edgeHubsSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable Copilot in Microsoft Edge. ähnelt.
        /// </summary>
        internal static string _edgeHubsSidebar_desc {
            get {
                return ResourceManager.GetString("_edgeHubsSidebar_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t Allow to Import of data from other browsers on each launch ähnelt.
        /// </summary>
        internal static string _edgeImportOnEachLaunch {
            get {
                return ResourceManager.GetString("_edgeImportOnEachLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow import of data from other browsers on each Microsoft Edge launch. ähnelt.
        /// </summary>
        internal static string _edgeImportOnEachLaunch_desc {
            get {
                return ResourceManager.GetString("_edgeImportOnEachLaunch_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Start Boost ähnelt.
        /// </summary>
        internal static string _edgeStartupBoost {
            get {
                return ResourceManager.GetString("_edgeStartupBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables Microsoft Edge processes to initialize at operating system startup and restart in the background after the last browser window has been closed. ähnelt.
        /// </summary>
        internal static string _edgeStartupBoost_desc {
            get {
                return ResourceManager.GetString("_edgeStartupBoost_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t Show Quick links in new tab page ähnelt.
        /// </summary>
        internal static string _edgeTabPageQuickLinks {
            get {
                return ResourceManager.GetString("_edgeTabPageQuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By default, when you open a new tab, you see a Bing search bar, Bing image of the day set as the page background. For supported websites, Quick Links on the New Tab page can display recent updates right in the tile. ähnelt.
        /// </summary>
        internal static string _edgeTabPageQuickLinks_desc {
            get {
                return ResourceManager.GetString("_edgeTabPageQuickLinks_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t Submit user feedback option ähnelt.
        /// </summary>
        internal static string _edgeUserFeedback {
            get {
                return ResourceManager.GetString("_edgeUserFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow the submission of feedback, suggestions, or customer surveys, as well as reporting issues with the browser. ähnelt.
        /// </summary>
        internal static string _edgeUserFeedback_desc {
            get {
                return ResourceManager.GetString("_edgeUserFeedback_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turn off GameDVR ähnelt.
        /// </summary>
        internal static string _gamingGameDVR {
            get {
                return ResourceManager.GetString("_gamingGameDVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable GameDVR. ähnelt.
        /// </summary>
        internal static string _gamingGameDVR_desc {
            get {
                return ResourceManager.GetString("_gamingGameDVR_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turn off PowerThrottling ähnelt.
        /// </summary>
        internal static string _gamingPowerThrottling {
            get {
                return ResourceManager.GetString("_gamingPowerThrottling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable PowerThrottling. ähnelt.
        /// </summary>
        internal static string _gamingPowerThrottling_desc {
            get {
                return ResourceManager.GetString("_gamingPowerThrottling_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable VisualFX ähnelt.
        /// </summary>
        internal static string _gamingVisualFX {
            get {
                return ResourceManager.GetString("_gamingVisualFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable VisualFX. ähnelt.
        /// </summary>
        internal static string _gamingVisualFX_desc {
            get {
                return ResourceManager.GetString("_gamingVisualFX_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Final checks in progress... ähnelt.
        /// </summary>
        internal static string _logFinalCheck {
            get {
                return ResourceManager.GetString("_logFinalCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All checks completed. ähnelt.
        /// </summary>
        internal static string _logFinalCheck_complete {
            get {
                return ResourceManager.GetString("_logFinalCheck_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you for using xd-AntiSpy! If you find this tool useful, consider donating to support its development: https://paypal.com/donate?hosted_button_id=MY7HX4QLYR4KG ähnelt.
        /// </summary>
        internal static string _logFinalCheckMessage {
            get {
                return ResourceManager.GetString("_logFinalCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Follow and contribute to the project on GitHub: https://github.com/builtbybel/xd-AntiSpy ähnelt.
        /// </summary>
        internal static string _logFinalCheckMessage2 {
            get {
                return ResourceManager.GetString("_logFinalCheckMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting native feature checks... ähnelt.
        /// </summary>
        internal static string _logNativeFeatureCheck {
            get {
                return ResourceManager.GetString("_logNativeFeatureCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feature checks completed. ähnelt.
        /// </summary>
        internal static string _logNativeFeatureCheck_complete {
            get {
                return ResourceManager.GetString("_logNativeFeatureCheck_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting plugin checks... ähnelt.
        /// </summary>
        internal static string _logPluginsFeatureCheck {
            get {
                return ResourceManager.GetString("_logPluginsFeatureCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin checks completed. ähnelt.
        /// </summary>
        internal static string _logPluginsFeatureCheck_complete {
            get {
                return ResourceManager.GetString("_logPluginsFeatureCheck_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Running apps in background ähnelt.
        /// </summary>
        internal static string _privacyBackgroundApps {
            get {
                return ResourceManager.GetString("_privacyBackgroundApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable running apps in background. ähnelt.
        /// </summary>
        internal static string _privacyBackgroundApps_desc {
            get {
                return ResourceManager.GetString("_privacyBackgroundApps_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Find my device ähnelt.
        /// </summary>
        internal static string _privacyFindMyDevice {
            get {
                return ResourceManager.GetString("_privacyFindMyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable find my device. ähnelt.
        /// </summary>
        internal static string _privacyFindMyDevice_desc {
            get {
                return ResourceManager.GetString("_privacyFindMyDevice_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Privacy Settings Experience at sign-in ähnelt.
        /// </summary>
        internal static string _privacyPrivacyExperience {
            get {
                return ResourceManager.GetString("_privacyPrivacyExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable Privacy Settings Experience at sign-in. ähnelt.
        /// </summary>
        internal static string _privacyPrivacyExperience_desc {
            get {
                return ResourceManager.GetString("_privacyPrivacyExperience_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turn off Telemetry data collection ähnelt.
        /// </summary>
        internal static string _privacyTelemetry {
            get {
                return ResourceManager.GetString("_privacyTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfortunately, Microsoft does not allow Windows 11 or Windows 10 Home edition users to completely turn off the collection of telemetry data. However, those users can still limit some optional data collection through System settings. ähnelt.
        /// </summary>
        internal static string _privacyTelemetry_desc {
            get {
                return ResourceManager.GetString("_privacyTelemetry_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall Fax Printer ähnelt.
        /// </summary>
        internal static string _systemFaxPrinter {
            get {
                return ResourceManager.GetString("_systemFaxPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will uninstall the Fax Printer. ähnelt.
        /// </summary>
        internal static string _systemFaxPrinter_desc {
            get {
                return ResourceManager.GetString("_systemFaxPrinter_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Full context menus in Windows 11 ähnelt.
        /// </summary>
        internal static string _systemFullContextMenus {
            get {
                return ResourceManager.GetString("_systemFullContextMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will enable full context menus in Windows 11. ähnelt.
        /// </summary>
        internal static string _systemFullContextMenus_desc {
            get {
                return ResourceManager.GetString("_systemFullContextMenus_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t use personalized lock screen ähnelt.
        /// </summary>
        internal static string _systemLockScreen {
            get {
                return ResourceManager.GetString("_systemLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable the personalized lock screen. ähnelt.
        /// </summary>
        internal static string _systemLockScreen_desc {
            get {
                return ResourceManager.GetString("_systemLockScreen_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display highly detailed status messages ähnelt.
        /// </summary>
        internal static string _systemVerboseMessages {
            get {
                return ResourceManager.GetString("_systemVerboseMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will display highly detailed status messages. ähnelt.
        /// </summary>
        internal static string _systemVerboseMessages_desc {
            get {
                return ResourceManager.GetString("_systemVerboseMessages_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall XPS Writer ähnelt.
        /// </summary>
        internal static string _systemXPSWriter {
            get {
                return ResourceManager.GetString("_systemXPSWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will uninstall the XPS Documents Writer. ähnelt.
        /// </summary>
        internal static string _systemXPSWriter_desc {
            get {
                return ResourceManager.GetString("_systemXPSWriter_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Bing Cloud content search ähnelt.
        /// </summary>
        internal static string _taskbarBingSearch {
            get {
                return ResourceManager.GetString("_taskbarBingSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable Bing Cloud content search. ähnelt.
        /// </summary>
        internal static string _taskbarBingSearch_desc {
            get {
                return ResourceManager.GetString("_taskbarBingSearch_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Most used apps in start menu ähnelt.
        /// </summary>
        internal static string _taskbarMostUsedApps {
            get {
                return ResourceManager.GetString("_taskbarMostUsedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will hide the most used apps in start menu. ähnelt.
        /// </summary>
        internal static string _taskbarMostUsedApps_desc {
            get {
                return ResourceManager.GetString("_taskbarMostUsedApps_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Searchbox on Taskbar ähnelt.
        /// </summary>
        internal static string _taskbarSearchbox {
            get {
                return ResourceManager.GetString("_taskbarSearchbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will remove Searchbox from the Taskbar. ähnelt.
        /// </summary>
        internal static string _taskbarSearchbox_desc {
            get {
                return ResourceManager.GetString("_taskbarSearchbox_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align Start button to left ähnelt.
        /// </summary>
        internal static string _taskbarStartButtonAlignment {
            get {
                return ResourceManager.GetString("_taskbarStartButtonAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will align the Start button to the left. ähnelt.
        /// </summary>
        internal static string _taskbarStartButtonAlignment_desc {
            get {
                return ResourceManager.GetString("_taskbarStartButtonAlignment_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin more Apps on Start menu ähnelt.
        /// </summary>
        internal static string _taskbarStartmenuLayout {
            get {
                return ResourceManager.GetString("_taskbarStartmenuLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will change the start layout to show more pins (and hide recommendations) in the Start menu. If disabled, more recommendations will be shown instead of pins. ähnelt.
        /// </summary>
        internal static string _taskbarStartmenuLayout_desc {
            get {
                return ResourceManager.GetString("_taskbarStartmenuLayout_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Chat icon on taskbar ähnelt.
        /// </summary>
        internal static string _taskbarTaskbarChat {
            get {
                return ResourceManager.GetString("_taskbarTaskbarChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By default, the chat feature allows you to access Microsoft Teams easily. But, if you don’t use Teams or just don’t want the icon on your taskbar, you can hide it. ähnelt.
        /// </summary>
        internal static string _taskbarTaskbarChat_desc {
            get {
                return ResourceManager.GetString("_taskbarTaskbarChat_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Task view button on taskbar ähnelt.
        /// </summary>
        internal static string _taskbarTaskView {
            get {
                return ResourceManager.GetString("_taskbarTaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable the task view button on the taskbar. ähnelt.
        /// </summary>
        internal static string _taskbarTaskView_desc {
            get {
                return ResourceManager.GetString("_taskbarTaskView_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Widgets from taskbar ähnelt.
        /// </summary>
        internal static string _taskbarWidgets {
            get {
                return ResourceManager.GetString("_taskbarWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will remove Widgets from the Taskbar. ähnelt.
        /// </summary>
        internal static string _taskbarWidgets_desc {
            get {
                return ResourceManager.GetString("_taskbarWidgets_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply Setting ähnelt.
        /// </summary>
        internal static string ctl_btnApply {
            get {
                return ResourceManager.GetString("ctl_btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (c)2024 A Belim app creation
        ///While there&apos;s no guarantee xD-Antispy will work perfectly on your system, I&apos;ve tested it extensively.  Remember, it&apos;s a one-person project and I&apos;m just human.
        ///
        ///This tool is open source and will always be free.  I&apos;m committed to keeping it updated and improving.
        ///
        ///xD-Antispy is a modern fork of the classic XP-Antispy for Windows 11, evolving to meet today&apos;s privacy challenges. 
        ///
        ///xD-Antispy – because privacy settings should make you smile!
        ///
        ///-Belim- ähnelt.
        /// </summary>
        internal static string formAbout_lblAbout {
            get {
                return ResourceManager.GetString("formAbout_lblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your support helps keep this app running and growing—thank you! — Belim ähnelt.
        /// </summary>
        internal static string formAbout_linkDonation {
            get {
                return ResourceManager.GetString("formAbout_linkDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Furthermore, AI-generated and verified plugins have been automatically loaded into the app&apos;s plugins folder. These plugins can be seamlessly integrated into the list view or accessed through the tools menu. Explore these enhancements to tailor your experience and optimize functionality effortlessly. ähnelt.
        /// </summary>
        internal static string formSymbolRef_checkInfoPlugins {
            get {
                return ResourceManager.GetString("formSymbolRef_checkInfoPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active: When an option is checked and grayed out, it means the setting is active. ähnelt.
        /// </summary>
        internal static string formSymbolRef_lblActive {
            get {
                return ResourceManager.GetString("formSymbolRef_lblActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember, keeping certain settings active can enhance your system&apos;s privacy and performance. Adjust these options according to your needs, and enjoy a more secure computing experience! ähnelt.
        /// </summary>
        internal static string formSymbolRef_lblGreen {
            get {
                return ResourceManager.GetString("formSymbolRef_lblGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inactive: If an option is unchecked and the text is in a normal color, the setting is inactive. You can enable it by simply checking the box and pressing the apply button. ähnelt.
        /// </summary>
        internal static string formSymbolRef_lblInactive {
            get {
                return ResourceManager.GetString("formSymbolRef_lblInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additionally, for this app, there are cool and recommended profiles available on various online communities like Reddit and Deskmodder. As the app is new and growing, if you&apos;re unsure about which settings to configure, checking out these profiles can provide valuable insights. Explore and discover optimal configurations that suit your preferences, ensuring a personalized and enhanced user experience! ähnelt.
        /// </summary>
        internal static string formSymbolRef_lblRed {
            get {
                return ResourceManager.GetString("formSymbolRef_lblRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt; Back ähnelt.
        /// </summary>
        internal static string formToolDebloater_btnBack {
            get {
                return ResourceManager.GetString("formToolDebloater_btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select custom db... ähnelt.
        /// </summary>
        internal static string formToolDebloater_btnChooseDB {
            get {
                return ResourceManager.GetString("formToolDebloater_btnChooseDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove selected apps ähnelt.
        /// </summary>
        internal static string formToolDebloater_btnRemoveSelected {
            get {
                return ResourceManager.GetString("formToolDebloater_btnRemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deselect All ähnelt.
        /// </summary>
        internal static string formToolDebloater_DeselectAll {
            get {
                return ResourceManager.GetString("formToolDebloater_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select at least one app to remove. ähnelt.
        /// </summary>
        internal static string formToolDebloater_errorNoAppsCount {
            get {
                return ResourceManager.GetString("formToolDebloater_errorNoAppsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select All ähnelt.
        /// </summary>
        internal static string formToolDebloater_selectAll {
            get {
                return ResourceManager.GetString("formToolDebloater_selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check completed. ähnelt.
        /// </summary>
        internal static string formToolDebloater_statusCheckComplete {
            get {
                return ResourceManager.GetString("formToolDebloater_statusCheckComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking ähnelt.
        /// </summary>
        internal static string formToolDebloater_statusChecking {
            get {
                return ResourceManager.GetString("formToolDebloater_statusChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die removed. ähnelt.
        /// </summary>
        internal static string formToolDebloater_statusRemoved {
            get {
                return ResourceManager.GetString("formToolDebloater_statusRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removing ähnelt.
        /// </summary>
        internal static string formToolDebloater_statusRemoving {
            get {
                return ResourceManager.GetString("formToolDebloater_statusRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apps successfully removed. ähnelt.
        /// </summary>
        internal static string formToolDebloater_successRemoved {
            get {
                return ResourceManager.GetString("formToolDebloater_successRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About XDAntiSpy... ähnelt.
        /// </summary>
        internal static string menu_aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy to clipboard ähnelt.
        /// </summary>
        internal static string menu_copySettingsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_copySettingsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export current ähnelt.
        /// </summary>
        internal static string menu_exportCurrentSettingsStripMenuItem {
            get {
                return ResourceManager.GetString("menu_exportCurrentSettingsStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit GitHub site ähnelt.
        /// </summary>
        internal static string menu_gitHubSiteToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_gitHubSiteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ? ähnelt.
        /// </summary>
        internal static string menu_helpToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_helpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        internal static string menu_importSettingsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_importSettingsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open plugins directory ähnelt.
        /// </summary>
        internal static string menu_openPluginsDirectoryToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_openPluginsDirectoryToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profiles ähnelt.
        /// </summary>
        internal static string menu_profilesToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_profilesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        internal static string menu_refreshToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_refreshToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search for crappy apps ähnelt.
        /// </summary>
        internal static string menu_searchForCrappyAppsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_searchForCrappyAppsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Share on X... ähnelt.
        /// </summary>
        internal static string menu_shareSettingsOnXTwitterToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_shareSettingsOnXTwitterToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Symbol Reference... ähnelt.
        /// </summary>
        internal static string menu_symbolrefToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_symbolrefToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        /// </summary>
        internal static string menu_toolsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_toolsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update... ähnelt.
        /// </summary>
        internal static string menu_updateToolStripMenuItem {
            get {
                return ResourceManager.GetString("menu_updateToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Setting Manually ähnelt.
        /// </summary>
        internal static string menuDoContextItem {
            get {
                return ResourceManager.GetString("menuDoContextItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin ähnelt.
        /// </summary>
        internal static string menuPinContextItem {
            get {
                return ResourceManager.GetString("menuPinContextItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Setting ähnelt.
        /// </summary>
        internal static string menuUndoContextItem {
            get {
                return ResourceManager.GetString("menuUndoContextItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Applied: ähnelt.
        /// </summary>
        internal static string statusApplied {
            get {
                return ResourceManager.GetString("statusApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disabled ähnelt.
        /// </summary>
        internal static string statusDisabled {
            get {
                return ResourceManager.GetString("statusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enabled ähnelt.
        /// </summary>
        internal static string statusEnabled {
            get {
                return ResourceManager.GetString("statusEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die has been ähnelt.
        /// </summary>
        internal static string statusHasBeen {
            get {
                return ResourceManager.GetString("statusHasBeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is currently ähnelt.
        /// </summary>
        internal static string statusIsCurrently {
            get {
                return ResourceManager.GetString("statusIsCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die has been disabled. ähnelt.
        /// </summary>
        internal static string statusIsDisabled {
            get {
                return ResourceManager.GetString("statusIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die has been enabled. ähnelt.
        /// </summary>
        internal static string statusIsEnabled {
            get {
                return ResourceManager.GetString("statusIsEnabled", resourceCulture);
            }
        }
    }
}
